id = {
    "data": [
        {
            "cc1": "gb",
            "city_name": "London",
            "city_ufi": -2601889,
            "country": "United Kingdom",
            "dest_id": "2280",
            "dest_type": "district",
            "hotels": 2155,
            "image_url": "https://cf.bstatic.com/xdata/images/district/150x150/56431.jpg?k=c580405cbf1e9c2cf17fd39015b08d13a04589a72afab80bb9419b6bfcebdd51&o=",
            "label": "Central London, London, Greater London, United Kingdom",
            "latitude": 51.507282,
            "lc": "en",
            "longitude": -0.13493559,
            "name": "Central London",
            "nr_hotels": 2155,
            "region": "Greater London",
            "roundtrip": "GgEwIAAoATICZW46BkxvbmRvbkAASgBQAA==",
            "search_type": "district",
            "type": "di"
        },
        {
            "cc1": "gb",
            "city_name": "London",
            "city_ufi": None,
            "country": "United Kingdom",
            "dest_id": "-2601889",
            "dest_type": "city",
            "hotels": 14500,
            "image_url": "https://cf.bstatic.com/xdata/images/city/150x150/977261.jpg?k=6e056b414cda72f979d7227aff6f5cb43035a30555649dce0292bae146ba4d57&o=",
            "label": "London, Greater London, United Kingdom",
            "latitude": 51.50739,
            "lc": "en",
            "longitude": -0.12763432,
            "name": "London",
            "nr_hotels": 14500,
            "region": "Greater London",
            "roundtrip": "GgEwIAEoATICZW46BkxvbmRvbkAASgBQAA==",
            "search_type": "city",
            "type": "ci"
        },
        {
            "cc1": "gb",
            "city_name": "London",
            "city_ufi": -2601889,
            "country": "United Kingdom",
            "dest_id": "4",
            "dest_type": "airport",
            "hotels": 93,
            "image_url": "https://cf.bstatic.com/static/img/plane-100.jpg",
            "label": "London Heathrow Airport, London, Greater London, United Kingdom",
            "latitude": 51.4713,
            "lc": "en",
            "longitude": -0.452693,
            "name": "London Heathrow Airport",
            "nr_hotels": 93,
            "region": "Greater London",
            "roundtrip": "GgEwIAIoATICZW46BkxvbmRvbkAASgBQAA==",
            "search_type": "airport",
            "type": "ai"
        },
        {
            "cc1": "gb",
            "city_name": "London",
            "city_ufi": -2601889,
            "country": "United Kingdom",
            "dest_id": "20",
            "dest_type": "airport",
            "hotels": 16,
            "image_url": "https://cf.bstatic.com/static/img/plane-100.jpg",
            "label": "London Gatwick Airport, London, Greater London, United Kingdom",
            "latitude": 51.1584,
            "lc": "en",
            "longitude": -0.169334,
            "name": "London Gatwick Airport",
            "nr_hotels": 16,
            "region": "Greater London",
            "roundtrip": "GgEwIAMoATICZW46BkxvbmRvbkAASgBQAA==",
            "search_type": "airport",
            "type": "ai"
        },
        {
            "cc1": "gb",
            "city_name": "London",
            "city_ufi": -2601889,
            "country": "United Kingdom",
            "dest_id": "75",
            "dest_type": "airport",
            "hotels": 54,
            "image_url": "https://cf.bstatic.com/static/img/plane-100.jpg",
            "label": "London Stansted Airport, London, Greater London, United Kingdom",
            "latitude": 51.8895,
            "lc": "en",
            "longitude": 0.262084,
            "name": "London Stansted Airport",
            "nr_hotels": 54,
            "region": "Greater London",
            "roundtrip": "GgEwIAQoATICZW46BkxvbmRvbkAASgBQAA==",
            "search_type": "airport",
            "type": "ai"
        }
    ],
    "message": "Success",
    "status": True,
    "timestamp": 1726209432012
}
print(id['data'][0]['dest_id'])
